# Generated by Django 4.2 on 2023-06-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz_section_course_specific_content_subsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
