# Generated by Django 4.2 on 2023-06-05 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_quizquestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsection',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='SubSection',
        ),
    ]
