# Generated by Django 4.2 on 2023-06-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_subsection_section_delete_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.DeleteModel(
            name='QuizAnswer',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
    ]
