# Generated by Django 4.2 on 2023-06-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_quiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='gif',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
