# Generated by Django 4.2 on 2023-06-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_quizcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_audios/'),
        ),
    ]
