# Generated by Django 4.2 on 2023-05-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_teammember_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
